# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

# orbs:
#   python: circleci/python@2.0.3
 
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
version: 2.1
jobs:
    build:
      docker:
        - image: circleci/python:3.7
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    #
      working_directory: ~/devops
      steps:
        - checkout
        - run:
            name: install dependencies
            command: |
                python3 -m venv venv
                . venv/bin/activate
                pip3 install pytest pytest-cov
                pip3 install flake8
                pip3 freeze
                pip3 freeze > requirements.txt
                # sudo apt install python3-brlapi
                pip install -r requirements.txt
          
        - run:
            name: run tests
            command: |
                . venv/bin/activate
                flake8 --exclude venv --ignore=E501,F401
                python -m pytest -o junit_family=xunit1 --junitxml=test-reports/junit.xml
    #1 Obtain repo from Github
      
   #2 Create a virtual environment and install dependencies
          
#3 Run coding convention software plus tester.
      
 
        - store_test_results:
            path: test-results
        - store_artifacts:
            path: test-results
